# Generated by Django 4.1.1 on 2022-10-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPickers', '0001_initial'),
        ('bazaar', '0010_rename_groups_bazaar_groupscategoties'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
        migrations.AddField(
            model_name='user',
            name='allocatedCities',
            field=models.ManyToManyField(blank=True, related_name='allocatedCities', to='defaultPickers.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='allocatedDistricts',
            field=models.ManyToManyField(blank=True, related_name='allocatedDistricts', to='defaultPickers.district'),
        ),
        migrations.AddField(
            model_name='user',
            name='allocatedStates',
            field=models.ManyToManyField(blank=True, related_name='allocatedStates', to='defaultPickers.state'),
        ),
        migrations.AddField(
            model_name='user',
            name='bazaars',
            field=models.ManyToManyField(blank=True, to='bazaar.bazaar'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
