# Generated by Django 4.1.1 on 2022-10-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customertype_remove_user_allocatedcities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
