# Generated by Django 4.1.1 on 2022-10-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_agent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
    ]
