# Generated by Django 3.2.15 on 2022-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('defaultPickers', '0001_initial'),
        ('bazaar', '0007_remove_productsubcategory_mrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=150)),
                ('amount', models.IntegerField(null=True)),
                ('branches', models.IntegerField(null=True)),
                ('user_per_branch', models.IntegerField(null=True)),
                ('plan_type', models.IntegerField(choices=[(0, 'Free'), (1, 'Paid')])),
                ('start_date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bazaars', models.ManyToManyField(to='bazaar.Bazaar')),
                ('cities', models.ManyToManyField(to='defaultPickers.City')),
                ('districts', models.ManyToManyField(to='defaultPickers.District')),
                ('features', models.ManyToManyField(to='plan.PlanFeature')),
                ('states', models.ManyToManyField(to='defaultPickers.State')),
            ],
        ),
    ]
