# Generated by Django 3.2.15 on 2022-09-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_remove_productsubcategory_mrp_and_more'),
        ('defaultPickers', '0001_initial'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='firm_name',
            new_name='plan_name',
        ),
        migrations.AlterField(
            model_name='plan',
            name='bazaars',
            field=models.ManyToManyField(null=True, to='bazaar.Bazaar'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cities',
            field=models.ManyToManyField(null=True, to='defaultPickers.City'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='districts',
            field=models.ManyToManyField(null=True, to='defaultPickers.District'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='states',
            field=models.ManyToManyField(null=True, to='defaultPickers.State'),
        ),
    ]
