# Generated by Django 3.2.15 on 2022-09-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0007_remove_productsubcategory_mrp_and_more'),
        ('defaultPickers', '0001_initial'),
        ('plan', '0002_auto_20220930_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='bazaars',
            field=models.ManyToManyField(blank=True, to='bazaar.Bazaar'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='cities',
            field=models.ManyToManyField(blank=True, to='defaultPickers.City'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='districts',
            field=models.ManyToManyField(blank=True, to='defaultPickers.District'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='states',
            field=models.ManyToManyField(blank=True, to='defaultPickers.State'),
        ),
    ]
