# Generated by Django 4.1.1 on 2022-09-25 09:39

import bazaar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazaar',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=bazaar.models.bazaarImage),
        ),
    ]
