# Generated by Django 4.1.1 on 2022-09-25 10:18

import bazaar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_bazaar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='backImage',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=bazaar.models.productImage),
        ),
        migrations.AddField(
            model_name='product',
            name='frontImage',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=bazaar.models.productImage),
        ),
        migrations.AddField(
            model_name='product',
            name='mrpImage',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=bazaar.models.productImage),
        ),
    ]
