# Generated by Django 4.1.1 on 2022-09-25 10:30

import bazaar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0003_product_backimage_product_frontimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=bazaar.models.bazaarGroupImage),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='gst',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='hsnCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=bazaar.models.productCategoryImage),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=bazaar.models.productSubCategoryImage),
        ),
    ]
