# Generated by Django 4.1.1 on 2022-09-25 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPickers', '0001_initial'),
        ('bazaar', '0004_group_image_product_brand_product_gst_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazaar',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bazaar',
            name='dist',
        ),
        migrations.AlterField(
            model_name='bazaar',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='defaultPickers.state'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='city',
            field=models.ManyToManyField(to='defaultPickers.city'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='dist',
            field=models.ManyToManyField(to='defaultPickers.district'),
        ),
    ]
