# Generated by Django 4.1.1 on 2022-09-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0006_productquantityunit_rename_group_groupcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubcategory',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='per_unit_weight',
        ),
        migrations.RemoveField(
            model_name='productsubcategory',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='per_unit_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bazaar.productquantityunit'),
        ),
    ]
