# Generated by Django 3.2.15 on 2022-09-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defaultPickers', '0001_initial'),
        ('bazaar', '0008_auto_20220930_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bazaar',
            old_name='district',
            new_name='districts',
        ),
        migrations.RenameField(
            model_name='bazaar',
            old_name='group',
            new_name='groups',
        ),
        migrations.RemoveField(
            model_name='bazaar',
            name='city',
        ),
        migrations.RemoveField(
            model_name='bazaar',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bazaar',
            name='productCategory',
        ),
        migrations.RemoveField(
            model_name='bazaar',
            name='productSubCategory',
        ),
        migrations.RemoveField(
            model_name='bazaar',
            name='state',
        ),
        migrations.AddField(
            model_name='bazaar',
            name='cities',
            field=models.ManyToManyField(to='defaultPickers.City'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='productCategories',
            field=models.ManyToManyField(to='bazaar.ProductCategory'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='productSubCategories',
            field=models.ManyToManyField(to='bazaar.ProductSubCategory'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='products',
            field=models.ManyToManyField(to='bazaar.Product'),
        ),
        migrations.AddField(
            model_name='bazaar',
            name='states',
            field=models.ManyToManyField(to='defaultPickers.State'),
        ),
    ]
