# Generated by Django 3.2.15 on 2022-09-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0009_auto_20220930_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bazaar',
            old_name='groups',
            new_name='groupsCategoties',
        ),
    ]
